'use client'
import './globals.css'
import React, { useEffect, useState } from 'react';

interface ClusterInfo {
  name: string;
  version: string;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [projectName, setProjectName] = useState<string>('');

  useEffect(() => {
    const fetchClusterInfo = async () => {
      try {
        const response = await fetch(process.env.NEXT_PUBLIC_CLUSTER_INFO_ENDPOINT!);
        const data = await response.json();
        setProjectName(data.name);
      } catch (error) {
        console.error('Error fetching cluster info:', error);
      }
    };

    fetchClusterInfo();
  }, []);

  return (
    <html lang="en">
      <head>
        <title>{projectName }</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
